# Brewfile
tap "puma/puma"
tap "heroku/brew"
tap "homebrew/core"
tap "homebrew/versions"
tap "homebrew/bundle"
tap "homebrew/services"
tap "caskroom/versions"
tap "caskroom/cask"
# cask "xquartz"
cask "caskroom/versions/java8"
brew "awscli"
brew "docker"
brew "docker-machine"
# brew "elasticsearch", link: false
brew "exiv2"
brew "fzf"
# brew "geckodriver"
brew "gpgme"
# brew "hub"
brew "imagemagick" #, args: ["with-x11"]
brew "libmaxminddb"
brew "libyaml"
brew "mysql", restart_service: true
brew "plantuml"
brew "postgresql", restart_service: true
brew "pv"
brew "rbenv"
brew "redis", restart_service: true
# brew "socat"
brew "yarn"
brew "zsh"
brew "zsh-completions"
brew "heroku/brew/heroku"
brew "puma/puma/puma-dev"
brew "thiswayq/versions-1/elasticsearch17"
cask "1password"
cask "adobe-acrobat-reader"
cask "aws-vault"
# cask "firefox"
cask "iterm2"
cask "keybase"
cask "slack"
cask "telegram"
cask "virtualbox"
cask "visual-studio-code"
cask "google-chrome"